<?php

namespace Test\AbraFlexi\Relationship;

use AbraFlexi\Relationship\Mailer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-01-10 at 17:25:44.
 */
class MailerTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Mailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Mailer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Relationship\Mailer::addItem
     * @todo   Implement testaddItem().
     */
    public function testaddItem() {
        $this->assertEquals('', $this->object->addItem());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Relationship\Mailer::getCss
     * @todo   Implement testgetCss().
     */
    public function testgetCss() {
        $this->assertEquals('', $this->object->getCss());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

}
