<?php

namespace Test\AbraFlexi\Relationship\ui;

use AbraFlexi\Relationship\ui\OptionsForm;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-01-10 at 17:25:44.
 */
class OptionsFormTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var OptionsForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new OptionsForm();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
