<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://github.com/VitexSoftware/AbraFlexi-RelationshipOverview
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi\Relationship;

use AbraFlexi\Relationship\Digestor;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-01-10 at 17:25:44.
 */
class DigestorTest extends \PHPUnit\Framework\TestCase
{
    protected Digestor $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Digestor();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::addHeading
     *
     * @todo   Implement testaddHeading().
     */
    public function testaddHeading(): void
    {
        $this->assertEquals('', $this->object->addHeading());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::dig
     *
     * @todo   Implement testdig().
     */
    public function testdig(): void
    {
        $this->assertEquals('', $this->object->dig());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::processModules
     *
     * @todo   Implement testprocessModules().
     */
    public function testprocessModules(): void
    {
        $this->assertEquals('', $this->object->processModules());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::getModules
     *
     * @todo   Implement testgetModules().
     */
    public function testgetModules(): void
    {
        $this->assertEquals('', $this->object->getModules());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::addToIndex
     *
     * @todo   Implement testaddToIndex().
     */
    public function testaddToIndex(): void
    {
        $this->assertEquals('', $this->object->addToIndex());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::addIndex
     *
     * @todo   Implement testaddIndex().
     */
    public function testaddIndex(): void
    {
        $this->assertEquals('', $this->object->addIndex());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::sendByMail
     *
     * @todo   Implement testsendByMail().
     */
    public function testsendByMail(): void
    {
        $this->assertEquals('', $this->object->sendByMail());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::saveToHtml
     *
     * @todo   Implement testsaveToHtml().
     */
    public function testsaveToHtml(): void
    {
        $this->assertEquals('', $this->object->saveToHtml());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::getWebPageInlineCSS
     *
     * @todo   Implement testgetWebPageInlineCSS().
     */
    public function testgetWebPageInlineCSS(): void
    {
        $this->assertEquals('', $this->object->getWebPageInlineCSS());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::getCustomCss
     *
     * @todo   Implement testgetCustomCss().
     */
    public function testgetCustomCss(): void
    {
        $this->assertEquals('', $this->object->getCustomCss());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::getAppVersion
     *
     * @todo   Implement testgetAppVersion().
     */
    public function testgetAppVersion(): void
    {
        $this->assertEquals('', $this->object->getAppVersion());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Relationship\Digestor::addFoot
     *
     * @todo   Implement testaddFoot().
     */
    public function testaddFoot(): void
    {
        $this->assertEquals('', $this->object->addFoot());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
